Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision "file", source: "./k8s_utility.sh", destination: "/tmp/k8s_utility.sh"  

  config.vm.define "master" do |master|
   master.vm.hostname = "master"
   master.vm.network "private_network", ip: "192.168.56.10"
   master.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
    end
   master.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install net-tools
    apt install python3 python3-pip -y
    echo -e "Laboratorio1\nLaboratorio1" | passwd root
    swapoff -a
  SHELL
   end

  config.vm.define "worker01" do |worker01|
   worker01.vm.hostname = "worker01"
   worker01.vm.network "private_network", ip: "192.168.56.11"
   worker01.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
   end
   worker01.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install net-tools
    apt install python3 python3-pip -y
    echo -e "Laboratorio1\nLaboratorio1" | passwd root
    swapoff -a
  SHELL
  end

  config.vm.define "worker02" do |worker02|
   worker02.vm.hostname = "worker02"
   worker02.vm.network "private_network", ip: "192.168.56.12"
   worker02.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
   end   
   worker02.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install net-tools
    apt install python3 python3-pip -y
    echo -e "Laboratorio1\nLaboratorio1" | passwd root
    swapoff -a
  SHELL
  end
end